name: sudo
on:
  [workflow_dispatch, pull_request]
   
permissions:
  contents: read

jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest] # ubuntu-22.04
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Get sudo file
        run: |
          sudo ls /etc/sudoers.d
          sudo rm /etc/sudoers.d/runner
          sudo ls /etc/sudoers.d
          sudo less /etc/sudoers.d/90-cloud-init-users
